// Quiz data — Singapore childhood, 1950s–1980s.
// Images sourced & HTTP-200-verified from Wikimedia Commons.
// Answer choices audited for cultural accuracy: the correct answer is unambiguous
// and distractors are plausible-but-clearly-different items of the same kind.
window.QUIZZES = {

  // ---------------------------------------------------------------- GAMES
  games: {
    title: "Guess the Childhood Game",
    subtitle: "Kampong games  •  Singapore 1950s–1980s",
    items: [
      { name: "Chapteh",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Jianzi_players.jpg",
        credit: "Wikimedia Commons",
        choices: ["Five Stones", "Chapteh", "Goli", "Gasing"], correct: 1 },
      { name: "Goli (Marbles)",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/22/Playing_with_glass_marbles.jpg",
        credit: "Wikimedia Commons",
        choices: ["Goli (Marbles)", "Kuti-Kuti", "Chapteh", "Five Stones"], correct: 0 },
      { name: "Hopscotch",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/82/Hopscotch_de_Cubanese.jpg",
        credit: "Wikimedia Commons",
        choices: ["Hopscotch", "Congkak", "Catching", "Goli"], correct: 0 },
      { name: "Gasing (Spinning Top)",
        image: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Permainan_Tradisional_Gasing.jpg",
        credit: "Wikimedia Commons",
        choices: ["Chapteh", "Gasing (Spinning Top)", "Goli", "Congkak"], correct: 1 },
      { name: "Picture Cards (Gambar)",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Menko-square-circle-collection.jpg",
        credit: "Wikimedia Commons",
        choices: ["Five Stones", "Picture Cards (Gambar)", "Goli", "Gasing"], correct: 1 },
      { name: "Congkak",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/36/YosriCongkak1.jpg",
        credit: "Wikimedia Commons",
        choices: ["Congkak", "Five Stones", "Gasing", "Goli"], correct: 0 },
      { name: "Catching (Tag)",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/46/Jongensspelen_10.jpg",
        credit: "Wikimedia Commons",
        choices: ["Gasing", "Five Stones", "Catching (Tag)", "Goli"], correct: 2 }
    ]
  },

  // -------------------------------------------------------------- HAWKERS
  hawkers: {
    title: "Guess the Street Hawker & Treat",
    subtitle: "Old Singapore  •  1950s–1980s",
    items: [
      { name: "Ice-Cream Uncle",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Ice-cream_uncle_at_the_Helix_bridge_20230617_01.jpg",
        credit: "Wikimedia Commons",
        choices: ["Satay Man", "Ice-Cream Uncle", "Kacang Puteh Seller", "Karung Guni"], correct: 1 },
      { name: "Kacang Puteh",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Love_kacang_puteh.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kacang Puteh", "Kueh Tutu", "Tau Huey", "Putu Mayam"], correct: 0 },
      { name: "Satay",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Cooking_Chicken_Satay.jpg",
        credit: "Wikimedia Commons",
        choices: ["Otah", "Wanton Mee", "Satay", "Rojak"], correct: 2 },
      { name: "Tau Huey (Beancurd)",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e4/David_enjoying_D%C3%B2uhu%C4%81.jpg",
        credit: "Wikimedia Commons",
        choices: ["Cheng Tng", "Chendol", "Ice Kachang", "Tau Huey (Beancurd)"], correct: 3 },
      { name: "Ice Kachang",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/38/Ais_kacang.jpg",
        credit: "Wikimedia Commons",
        choices: ["Ice Kachang", "Chendol", "Cheng Tng", "Tau Huey"], correct: 0 },
      { name: "Karung Guni",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Karangguni.JPG",
        credit: "Wikimedia Commons",
        choices: ["Knife Sharpener", "Karung Guni", "Satay Man", "Tinsmith"], correct: 1 },
      { name: "Knife Sharpener",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/KITLV_-_50183_-_Lambert_%26_Co.%2C_G.R._-_Singapore_-_Malaysian_knife_sharpeners_in_Singapore_-_circa_1900.tif/lossy-page1-1280px-KITLV_-_50183_-_Lambert_%26_Co.%2C_G.R._-_Singapore_-_Malaysian_knife_sharpeners_in_Singapore_-_circa_1900.tif.jpg",
        credit: "Wikimedia Commons",
        choices: ["Karung Guni", "Cobbler", "Knife Sharpener", "Ice-Cream Uncle"], correct: 2 },
      { name: "Putu Mayam",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Putu_mayam.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kueh Tutu", "Ang Ku Kueh", "Ondeh-Ondeh", "Putu Mayam"], correct: 3 },
      { name: "Wanton Mee",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/89/HK_SW_%E4%B8%8A%E7%92%B0_Sheung_Wan_%E7%9A%87%E5%90%8E%E5%A4%A7%E9%81%93%E4%B8%AD_303_Queen%27s_Road_Central_%E6%AC%8A%E8%A8%98%E9%9B%B2%E5%90%9E%E9%BA%B5_Wonton_noodle_soup_shop_June_2020_SS2_10.jpg",
        credit: "Wikimedia Commons",
        choices: ["Wanton Mee", "Mee Rebus", "Hokkien Mee", "Laksa"], correct: 0 },
      { name: "Kueh Tutu",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Tutu_Kueh.jpg",
        credit: "Wikimedia Commons",
        choices: ["Ang Ku Kueh", "Kueh Tutu", "Ondeh-Ondeh", "Putu Piring"], correct: 1 }
    ]
  },

  // ------------------------------------------------------------ HOUSEHOLD
  household: {
    title: "Guess the Old Household Object",
    subtitle: "Every kampong & HDB home  •  1950s–1980s",
    items: [
      { name: "Kerosene Stove",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/HK_Kerosene_Stove_HuoShuiLu_%E7%81%AB%E6%B0%B4%E7%88%90_3.JPG",
        credit: "Wikimedia Commons",
        choices: ["Charcoal Stove", "Kerosene Stove", "Gas Ring", "Clay Brazier"], correct: 1 },
      { name: "Charcoal Iron",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/62/Charcoal_iron_03.jpg",
        credit: "Wikimedia Commons",
        choices: ["Charcoal Iron", "Mangle", "Steam Press", "Flat Iron"], correct: 0 },
      { name: "Abacus",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/af/Abacus_6.png",
        credit: "Wikimedia Commons",
        choices: ["Cash Register", "Abacus", "Counting Board", "Ledger Frame"], correct: 1 },
      { name: "Rediffusion Box",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Rediffusion_set.jpg",
        credit: "Wikimedia Commons",
        choices: ["Transistor Radio", "Rediffusion Box", "Gramophone", "Loudspeaker"], correct: 1 },
      { name: "Mosquito Coil",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/87/Mosquito_coil.JPG",
        credit: "Wikimedia Commons",
        choices: ["Incense Coil", "Mosquito Coil", "Citronella Candle", "Joss Stick"], correct: 1 },
      { name: "Thermos Flask",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Vintage_Aladdin_Vacuum_Flas.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kettle", "Thermos Flask", "Tea Urn", "Enamel Jug"], correct: 1 },
      { name: "Wooden Clogs (Terompah)",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/TerompahQR.jpg",
        credit: "Wikimedia Commons",
        choices: ["Wooden Clogs (Terompah)", "Rattan Sandals", "Leather Slippers", "Straw Shoes"], correct: 0 },
      { name: "Tingkat (Tiffin Carrier)",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Pernakan_Tiffin_Carrier.png",
        credit: "Wikimedia Commons",
        choices: ["Lunch Box", "Tingkat (Tiffin Carrier)", "Mess Tin", "Bento Set"], correct: 1 },
      { name: "Enamel Mug",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Enamel_mug.jpg",
        credit: "Wikimedia Commons",
        choices: ["Tin Mug", "Enamel Mug", "Pewter Cup", "Aluminium Cup"], correct: 1 },
      { name: "Chamber Pot",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/45/Chamber_pot%2C_ondersteek.jpg",
        credit: "Wikimedia Commons",
        choices: ["Spittoon", "Chamber Pot", "Wash Basin", "Water Pail"], correct: 1 }
    ]
  },

  // ------------------------------------------------------- KUEH & DESSERTS
  kueh: {
    title: "Guess the Traditional Kueh",
    subtitle: "Kueh & desserts of old Singapore",
    items: [
      { name: "Ang Ku Kueh",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Kue_ku_Jakarta.JPG",
        credit: "Wikimedia Commons",
        choices: ["Ang Ku Kueh", "Ondeh-Ondeh", "Soon Kueh", "Putu Piring"], correct: 0 },
      { name: "Ondeh-Ondeh",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/15/Ondeh_ondeh_kueh.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kueh Dadar", "Ondeh-Ondeh", "Ang Ku Kueh", "Kueh Lapis"], correct: 1 },
      { name: "Kueh Lapis",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/98/Kue_Lapis.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kueh Lapis", "Kueh Salat", "Pulut Hitam", "Ang Ku Kueh"], correct: 0 },
      { name: "Kueh Salat (Seri Muka)",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/06/YosriKuihSeriMuka.jpg",
        credit: "Wikimedia Commons",
        choices: ["Ondeh-Ondeh", "Kueh Salat (Seri Muka)", "Kueh Dadar", "Putu Piring"], correct: 1 },
      { name: "Putu Piring",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/70/YosriPutuPiring2.jpg",
        credit: "Wikimedia Commons",
        choices: ["Putu Piring", "Ang Ku Kueh", "Soon Kueh", "Ondeh-Ondeh"], correct: 0 },
      { name: "Goreng Pisang (Banana Fritter)",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Banana_Fritters_and_tea.jpg",
        credit: "Wikimedia Commons",
        choices: ["Goreng Pisang (Banana Fritter)", "Soon Kueh", "Kueh Dadar", "Pulut Hitam"], correct: 0 },
      { name: "Teochew Kueh (Soon / Png Kueh)",
        image: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Assorted_Teochew_kueh.jpg",
        credit: "Wikimedia Commons",
        choices: ["Teochew Kueh (Soon / Png Kueh)", "Ang Ku Kueh", "Ondeh-Ondeh", "Goreng Pisang"], correct: 0 },
      { name: "Kueh Dadar",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/32/Kue_Dadar_Gulung.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kueh Lapis", "Kueh Dadar", "Ondeh-Ondeh", "Putu Piring"], correct: 1 },
      { name: "Pulut Hitam",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Bubuh_Injin_Bali_1.jpg",
        credit: "Wikimedia Commons",
        choices: ["Pulut Hitam", "Bubur Cha Cha", "Cheng Tng", "Chendol"], correct: 0 },
      { name: "Kueh Ubi (Tapioca Cake)",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/YosriBingkaUbi.jpg",
        credit: "Wikimedia Commons",
        choices: ["Ondeh-Ondeh", "Kueh Ubi (Tapioca Cake)", "Goreng Pisang", "Ang Ku Kueh"], correct: 1 }
    ]
  },

  // ----------------------------------------------------- OLD SG PLACES
  places: {
    title: "Guess the Old Singapore Place",
    subtitle: "Landmarks of old Singapore  •  many now gone",
    items: [
      { name: "National Theatre",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Singapore-National_Theater-1973-74-WUS08168.jpg/3840px-Singapore-National_Theater-1973-74-WUS08168.jpg",
        credit: "Wikimedia Commons",
        choices: ["Capitol Theatre", "National Theatre", "Victoria Theatre", "Kallang Theatre"], correct: 1 },
      { name: "Satay Club",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Singapore-Satay-1973-74-WUS08150.jpg",
        credit: "Wikimedia Commons",
        choices: ["Satay Club", "Change Alley", "Great World", "Clifford Pier"], correct: 0 },
      { name: "Great World Amusement Park",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/70/Great_World_Amusement_Park.jpg",
        credit: "Wikimedia Commons",
        choices: ["Great World Amusement Park", "Wonderland Park", "Happy World", "Beauty World"], correct: 0 },
      { name: "Old Kallang Airport",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Kallang_Airport_Terminal.jpg",
        credit: "Wikimedia Commons",
        choices: ["Old Kallang Airport", "Paya Lebar Airport", "Seletar Airport", "Clifford Pier"], correct: 0 },
      { name: "Change Alley",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Change_Alley_Singapore_street_sign_January_1965.jpg",
        credit: "Wikimedia Commons",
        choices: ["Change Alley", "Bugis Street", "Thieves Market", "High Street"], correct: 0 },
      { name: "Clifford Pier",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Clifford_Pier%2C_Dec_05.JPG",
        credit: "Wikimedia Commons",
        choices: ["Clifford Pier", "Collyer Quay", "Telok Ayer", "Boat Quay"], correct: 0 },
      { name: "Capitol Theatre",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Old_Capitol.JPG",
        credit: "Wikimedia Commons",
        choices: ["Capitol Theatre", "Cathay Cinema", "Lido", "Odeon"], correct: 0 },
      { name: "New World Amusement Park",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/New_World_Amusement_Park.jpg",
        credit: "Wikimedia Commons",
        choices: ["Great World", "New World Amusement Park", "Gay World", "Beauty World"], correct: 1 }
    ]
  },

  // --------------------------------------------------------- FESTIVE ITEMS
  festive: {
    title: "Guess the Festive Item",
    subtitle: "CNY · Hari Raya · Deepavali · Mid-Autumn",
    items: [
      { name: "Paper Lantern",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Mid-Autumn_Festival_8%2C_Chinatown%2C_Singapore%2C_Sep_06.JPG",
        credit: "Wikimedia Commons",
        choices: ["Paper Lantern", "Pelita", "Ang Pow", "Pussy Willow"], correct: 0 },
      { name: "Mooncake",
        image: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Mooncake_3-4%2C_lotus_seed_paste.jpg",
        credit: "Wikimedia Commons",
        choices: ["Pineapple Tart", "Mooncake", "Bak Kwa", "Ang Ku Kueh"], correct: 1 },
      { name: "Pelita (Oil Lamp)",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Hari_Raya_Pelita.jpg",
        credit: "Wikimedia Commons",
        choices: ["Pelita (Oil Lamp)", "Paper Lantern", "Mosquito Coil", "Joss Stick"], correct: 0 },
      { name: "Ketupat",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Ketupat2.jpg",
        credit: "Wikimedia Commons",
        choices: ["Ondeh-Ondeh", "Ketupat", "Bak Kwa", "Lemang"], correct: 1 },
      { name: "Bak Kwa",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/da/Bak_kwa.jpg",
        credit: "Wikimedia Commons",
        choices: ["Bak Kwa", "Satay", "Otah", "Pineapple Tart"], correct: 0 },
      { name: "Pineapple Tarts",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Tat_nanas_%28Pineapple_tart%29_20230425_084201.jpg/3840px-Tat_nanas_%28Pineapple_tart%29_20230425_084201.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kueh Tutu", "Pineapple Tarts", "Mooncake", "Ang Ku Kueh"], correct: 1 },
      { name: "Rangoli (Kolam)",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Diwali_Decorations_Kolam_Rangoli_with_five_lamps_on_top_India_2009.jpg",
        credit: "Wikimedia Commons",
        choices: ["Rangoli (Kolam)", "Pelita", "Pussy Willow", "Paper Lantern"], correct: 0 },
      { name: "Ang Pow (Red Packet)",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Ang_pow.jpg",
        credit: "Wikimedia Commons",
        choices: ["Ang Pow (Red Packet)", "Joss Paper", "Mooncake Box", "Pineapple Tart"], correct: 0 },
      { name: "Pussy Willow",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/94/Dyed_pussy_willows_for_chinese_new_year.jpg",
        credit: "Wikimedia Commons",
        choices: ["Pussy Willow", "Bamboo", "Rangoli", "Ketupat"], correct: 0 },
      { name: "Lion Dance",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/High-pole-lion-dance.jpg/3840px-High-pole-lion-dance.jpg",
        credit: "Wikimedia Commons",
        choices: ["Dragon Dance", "Lion Dance", "Wayang", "Getai"], correct: 1 }
    ]
  },

  // ------------------------------------------------------ MAMA SHOP TREATS
  mamashop: {
    title: "Guess the Mama Shop Treat",
    subtitle: "Provision & mama shop favourites",
    items: [
      { name: "White Rabbit Candy",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Tin_of_White_Rabbit_Sweets.jpg",
        credit: "Wikimedia Commons",
        choices: ["White Rabbit Candy", "Haw Flakes", "Iced Gems", "Kaya"], correct: 0 },
      { name: "Haw Flakes",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Hawflakes.jpg",
        credit: "Wikimedia Commons",
        choices: ["Haw Flakes", "White Rabbit Candy", "Sour Plum", "Iced Gems"], correct: 0 },
      { name: "Iced Gem Biscuits",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/66/Iced_Gems.jpg",
        credit: "Wikimedia Commons",
        choices: ["Iced Gem Biscuits", "Ang Ku Kueh", "Haw Flakes", "Kueh Tutu"], correct: 0 },
      { name: "Kacang Tumbuk (Peanut Candy)",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/YosriKacangTumbuk.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kacang Tumbuk (Peanut Candy)", "Ang Ku Kueh", "Ondeh-Ondeh", "Haw Flakes"], correct: 0 },
      { name: "Milo Tin",
        image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/1940s_Nestl%C3%A9_Milo_tin.jpg",
        credit: "Wikimedia Commons",
        choices: ["Milo Tin", "Biscuit Tin", "Kaya Jar", "Condensed Milk"], correct: 0 },
      { name: "Marble Soda Bottle",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Codd-neck_bottle_04.jpg",
        credit: "Wikimedia Commons",
        choices: ["Marble Soda Bottle", "Thermos Flask", "Kerosene Lamp", "Milk Bottle"], correct: 0 },
      { name: "Biscuit Tin",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/53/Tin_Box_Danish_Butter_Biscuits_01.jpg",
        credit: "Wikimedia Commons",
        choices: ["Biscuit Tin", "Milo Tin", "Condensed Milk", "Kaya Jar"], correct: 0 },
      { name: "Kaya (Coconut Jam)",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/db/Coconut_jam_from_Philippines.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kaya (Coconut Jam)", "Condensed Milk", "Sour Plum", "Haw Flakes"], correct: 0 },
      { name: "Sour Plum (Li Hing Mui)",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Chinese_preserved_plum_snack.jpg",
        credit: "Wikimedia Commons",
        choices: ["Sour Plum (Li Hing Mui)", "Haw Flakes", "Kaya", "White Rabbit Candy"], correct: 0 },
      { name: "Condensed Milk Tin",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Tin_of_condensed_milk.jpg",
        credit: "Wikimedia Commons",
        choices: ["Condensed Milk Tin", "Milo Tin", "Biscuit Tin", "Kaya Jar"], correct: 0 }
    ]
  },

  // ------------------------------------------------------------- OLD TOYS
  toys: {
    title: "Guess the Old Toy",
    subtitle: "Childhood toys  •  Singapore 1950s–1980s",
    items: [
      { name: "Kite (Layang-Layang)",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/96/Kitesflying.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kite (Layang-Layang)", "Pinwheel", "Paper Doll", "Kaleidoscope"], correct: 0 },
      { name: "Tin Toy",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/88/Antique_tin_toy_wind-up_clown_and_wind-up_mouse_%2825196969284%29.jpg",
        credit: "Wikimedia Commons",
        choices: ["Tin Toy", "Rocking Horse", "Cap Gun", "Yo-yo"], correct: 0 },
      { name: "Paper Dolls",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Norma-DOLLS.jpg",
        credit: "Wikimedia Commons",
        choices: ["Paper Dolls", "Masak-Masak", "Pinwheel", "Kaleidoscope"], correct: 0 },
      { name: "Pinwheel (Paper Windmill)",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Green_pinwheel.jpg",
        credit: "Wikimedia Commons",
        choices: ["Pinwheel (Paper Windmill)", "Kite", "Yo-yo", "Cap Gun"], correct: 0 },
      { name: "Cap Gun",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/03/Cap_gun.jpg",
        credit: "Wikimedia Commons",
        choices: ["Cap Gun", "Tin Toy", "Yo-yo", "Kaleidoscope"], correct: 0 },
      { name: "Yo-yo",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/24/Yo-Yo-Plastic-Toy-Green.jpg",
        credit: "Wikimedia Commons",
        choices: ["Yo-yo", "Pinwheel", "Marbles", "Cap Gun"], correct: 0 },
      { name: "Kaleidoscope",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Kaleidoscope_tube_1.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kaleidoscope", "Tin Toy", "Rocking Horse", "Pinwheel"], correct: 0 },
      { name: "Rocking Horse",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/72/Wooden_rocking_horse.jpg",
        credit: "Wikimedia Commons",
        choices: ["Rocking Horse", "Masak-Masak", "Tin Toy", "Paper Dolls"], correct: 0 },
      { name: "Masak-Masak (Toy Cooking Set)",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Cooking_set%2C_doll%27s_%28AM_2013.51.23-1%29.jpg",
        credit: "Wikimedia Commons",
        choices: ["Masak-Masak (Toy Cooking Set)", "Tin Toy", "Kaleidoscope", "Paper Dolls"], correct: 0 },
      { name: "Marbles (Goli)",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/38/Glass_Marbles.jpg",
        credit: "Wikimedia Commons",
        choices: ["Marbles (Goli)", "Yo-yo", "Kaleidoscope", "Pinwheel"], correct: 0 }
    ]
  },

  // --------------------------------------------------------- KAMPONG LIFE
  kampong: {
    title: "Guess the Kampong Scene",
    subtitle: "Village life in old Singapore",
    items: [
      { name: "Attap House",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/ec/YosriAtapNipah.jpg",
        credit: "Wikimedia Commons",
        choices: ["Attap House", "Bullock Cart", "Sampan", "Village Well"], correct: 0 },
      { name: "Village Well",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Public_well_in_Surouli_Bujurg_Village%2C_Uttar_Pradesh%2C_India.jpg",
        credit: "Wikimedia Commons",
        choices: ["Village Well", "Standpipe", "Sampan", "Charcoal Stove"], correct: 0 },
      { name: "Communal Standpipe",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/59/Jake_Ward_collects_water_in_a_bucket_from_a_village_tap._%2810705623996%29.jpg",
        credit: "Wikimedia Commons",
        choices: ["Communal Standpipe", "Village Well", "Outhouse", "Coconut Tree"], correct: 0 },
      { name: "Outhouse (Jamban)",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Jamban_Terapung_di_sungai_Barito.jpg",
        credit: "Wikimedia Commons",
        choices: ["Outhouse (Jamban)", "Attap House", "Sampan", "Village Well"], correct: 0 },
      { name: "Kampong Chickens",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Ayam_Kampung.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kampong Chickens", "Bullock Cart", "Coconut Tree", "Sampan"], correct: 0 },
      { name: "Sampan",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/73/Native_sampan%2C_Singapore_%28NYPL_Hades-2359726-4044491%29.jpg",
        credit: "Wikimedia Commons",
        choices: ["Sampan", "Bullock Cart", "Trishaw", "Attap House"], correct: 0 },
      { name: "Bullock Cart",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/KITLV_-_159505_-_Ox_carts_in_a_street_in_Singapore_-_circa_1900.jpg",
        credit: "Wikimedia Commons",
        choices: ["Bullock Cart", "Trishaw", "Sampan", "Rickshaw"], correct: 0 },
      { name: "Kampong Village",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Kampong_in_Braddell_Hill_Singapore_about_1964.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kampong Village", "Town Centre", "Fishing Port", "Market"], correct: 0 },
      { name: "Coconut Tree Climbing",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/67/Coconut_tree_climbing_DSCN0236.jpg",
        credit: "Wikimedia Commons",
        choices: ["Coconut Tree Climbing", "Rubber Tapping", "Padi Field", "Banana Tree"], correct: 0 },
      { name: "Charcoal Stove Kitchen",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Cooking_area_with_pans_and_charcoal_stoves.jpg",
        credit: "Wikimedia Commons",
        choices: ["Charcoal Stove Kitchen", "Hawker Stall", "Provision Shop", "Coffee Shop"], correct: 0 }
    ]
  }

};
