// Quiz data — Singapore childhood, 1950s–1980s.
// Images sourced & HTTP-200-verified from Wikimedia Commons.
// Answer choices audited for cultural accuracy: the correct answer is unambiguous
// and distractors are plausible-but-clearly-different items of the same kind.
window.QUIZZES = {

  // ---------------------------------------------------------------- GAMES
  games: {
    title: "Guess the Childhood Game",
    subtitle: "Kampong games  •  Singapore 1950s–1980s",
    items: [
      { name: "Chapteh",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Jianzi_players.jpg",
        credit: "Wikimedia Commons",
        choices: ["Five Stones", "Chapteh", "Goli", "Gasing"], correct: 1 },
      { name: "Goli (Marbles)",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/22/Playing_with_glass_marbles.jpg",
        credit: "Wikimedia Commons",
        choices: ["Goli (Marbles)", "Kuti-Kuti", "Chapteh", "Five Stones"], correct: 0 },
      { name: "Five Stones",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Gonggi_pebbles.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kuti-Kuti", "Five Stones (Batu Seremban)", "Hopscotch", "Gasing"], correct: 1 },
      { name: "Hopscotch",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/82/Hopscotch_de_Cubanese.jpg",
        credit: "Wikimedia Commons",
        choices: ["Hopscotch", "Congkak", "Catching", "Goli"], correct: 0 },
      { name: "Gasing (Spinning Top)",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/67/Gasing_Indah_5.jpg",
        credit: "Wikimedia Commons",
        choices: ["Chapteh", "Gasing (Spinning Top)", "Goli", "Congkak"], correct: 1 },
      { name: "Picture Cards (Gambar)",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Menko-square-circle-collection.jpg",
        credit: "Wikimedia Commons",
        choices: ["Five Stones", "Picture Cards (Gambar)", "Goli", "Gasing"], correct: 1 },
      { name: "Congkak",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/36/YosriCongkak1.jpg",
        credit: "Wikimedia Commons",
        choices: ["Congkak", "Five Stones", "Gasing", "Goli"], correct: 0 },
      { name: "Catching (Tag)",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/46/Jongensspelen_10.jpg",
        credit: "Wikimedia Commons",
        choices: ["Gasing", "Five Stones", "Catching (Tag)", "Goli"], correct: 2 }
    ]
  },

  // -------------------------------------------------------------- HAWKERS
  hawkers: {
    title: "Guess the Street Hawker & Treat",
    subtitle: "Old Singapore  •  1950s–1980s",
    items: [
      { name: "Ice-Cream Uncle",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Ice-cream_uncle_at_the_Helix_bridge_20230617_01.jpg",
        credit: "Wikimedia Commons",
        choices: ["Satay Man", "Ice-Cream Uncle", "Kacang Puteh Seller", "Karung Guni"], correct: 1 },
      { name: "Kacang Puteh",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Love_kacang_puteh.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kacang Puteh", "Kueh Tutu", "Tau Huey", "Putu Mayam"], correct: 0 },
      { name: "Satay",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Cooking_Chicken_Satay.jpg",
        credit: "Wikimedia Commons",
        choices: ["Otah", "Wanton Mee", "Satay", "Rojak"], correct: 2 },
      { name: "Tau Huey (Beancurd)",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e4/David_enjoying_D%C3%B2uhu%C4%81.jpg",
        credit: "Wikimedia Commons",
        choices: ["Cheng Tng", "Chendol", "Ice Kachang", "Tau Huey (Beancurd)"], correct: 3 },
      { name: "Ice Kachang",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/38/Ais_kacang.jpg",
        credit: "Wikimedia Commons",
        choices: ["Ice Kachang", "Chendol", "Cheng Tng", "Tau Huey"], correct: 0 },
      { name: "Karung Guni",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/8a/Karangguni.JPG",
        credit: "Wikimedia Commons",
        choices: ["Knife Sharpener", "Karung Guni", "Satay Man", "Tinsmith"], correct: 1 },
      { name: "Knife Sharpener",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Bicicletta_arrotino.jpg",
        credit: "Wikimedia Commons",
        choices: ["Karung Guni", "Cobbler", "Knife Sharpener", "Ice-Cream Uncle"], correct: 2 },
      { name: "Putu Mayam",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Putu_mayam.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kueh Tutu", "Ang Ku Kueh", "Ondeh-Ondeh", "Putu Mayam"], correct: 3 },
      { name: "Wanton Mee",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/89/HK_SW_%E4%B8%8A%E7%92%B0_Sheung_Wan_%E7%9A%87%E5%90%8E%E5%A4%A7%E9%81%93%E4%B8%AD_303_Queen%27s_Road_Central_%E6%AC%8A%E8%A8%98%E9%9B%B2%E5%90%9E%E9%BA%B5_Wonton_noodle_soup_shop_June_2020_SS2_10.jpg",
        credit: "Wikimedia Commons",
        choices: ["Wanton Mee", "Mee Rebus", "Hokkien Mee", "Laksa"], correct: 0 },
      { name: "Kueh Tutu",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Tutu_Kueh.jpg",
        credit: "Wikimedia Commons",
        choices: ["Ang Ku Kueh", "Kueh Tutu", "Ondeh-Ondeh", "Putu Piring"], correct: 1 }
    ]
  },

  // ------------------------------------------------------------ HOUSEHOLD
  household: {
    title: "Guess the Old Household Object",
    subtitle: "Every kampong & HDB home  •  1950s–1980s",
    items: [
      { name: "Kerosene Stove",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/HK_Kerosene_Stove_HuoShuiLu_%E7%81%AB%E6%B0%B4%E7%88%90_3.JPG",
        credit: "Wikimedia Commons",
        choices: ["Charcoal Stove", "Kerosene Stove", "Gas Ring", "Clay Brazier"], correct: 1 },
      { name: "Charcoal Iron",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/62/Charcoal_iron_03.jpg",
        credit: "Wikimedia Commons",
        choices: ["Charcoal Iron", "Mangle", "Steam Press", "Flat Iron"], correct: 0 },
      { name: "Abacus",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/af/Abacus_6.png",
        credit: "Wikimedia Commons",
        choices: ["Cash Register", "Abacus", "Counting Board", "Ledger Frame"], correct: 1 },
      { name: "Rediffusion Box",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Rediffusion_set.jpg",
        credit: "Wikimedia Commons",
        choices: ["Transistor Radio", "Rediffusion Box", "Gramophone", "Loudspeaker"], correct: 1 },
      { name: "Mosquito Coil",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/87/Mosquito_coil.JPG",
        credit: "Wikimedia Commons",
        choices: ["Incense Coil", "Mosquito Coil", "Citronella Candle", "Joss Stick"], correct: 1 },
      { name: "Thermos Flask",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Vintage_Aladdin_Vacuum_Flas.jpg",
        credit: "Wikimedia Commons",
        choices: ["Kettle", "Thermos Flask", "Tea Urn", "Enamel Jug"], correct: 1 },
      { name: "Wooden Clogs (Terompah)",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/TerompahQR.jpg",
        credit: "Wikimedia Commons",
        choices: ["Wooden Clogs (Terompah)", "Rattan Sandals", "Leather Slippers", "Straw Shoes"], correct: 0 },
      { name: "Tingkat (Tiffin Carrier)",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Pernakan_Tiffin_Carrier.png",
        credit: "Wikimedia Commons",
        choices: ["Lunch Box", "Tingkat (Tiffin Carrier)", "Mess Tin", "Bento Set"], correct: 1 },
      { name: "Enamel Mug",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Enamel_mug.jpg",
        credit: "Wikimedia Commons",
        choices: ["Tin Mug", "Enamel Mug", "Pewter Cup", "Aluminium Cup"], correct: 1 },
      { name: "Chamber Pot",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/45/Chamber_pot%2C_ondersteek.jpg",
        credit: "Wikimedia Commons",
        choices: ["Spittoon", "Chamber Pot", "Wash Basin", "Water Pail"], correct: 1 }
    ]
  }

};
